// dm-data.js — LinkedIn DM categories + mock threads for the Approval Queue
window.DM_CATEGORIES = {
  investor:    { label: 'INVESTOR',    color: '#C8F902', bg: 'rgba(200,249,2,0.16)',  border: 'rgba(200,249,2,0.45)' },
  candidate:   { label: 'CANDIDATE',   color: '#D9E879', bg: 'rgba(217,232,121,0.14)',  border: 'rgba(217,232,121,0.40)' },
  'founder-peer': { label: 'FOUNDER-PEER', color: '#6FB4D9', bg: 'rgba(111,180,217,0.12)', border: 'rgba(111,180,217,0.40)' },
  vendor:      { label: 'VENDOR',      color: '#E8A91C', bg: 'rgba(232,169,28,0.12)', border: 'rgba(232,169,28,0.40)' },
  noise:       { label: 'NOISE',       color: '#8FA89A', bg: 'rgba(244,241,232,0.06)', border: 'rgba(244,241,232,0.16)' },
};

window.DM_THREADS = [
  { id: 't1', name: 'Aileen Cruz', role: 'Partner, Sequoia',
    cat: 'investor', time: '07:12',
    preview: 'Following on Series B timeline — open to a chat next week?',
    fullMessage: "Following on Series B timeline — open to a chat next week? Have a few thoughts on positioning that might be useful given how Sequoia's been thinking about the category.",
    draft: "Thanks Aileen. We're targeting a Series B in Q3, post the v2 launch. Happy to share the deck — would Tuesday at 11 work?",
    confidence: 0.91,
    reasoning: 'Verified Sequoia partner · Past warm intro from Mike · Series B fits stage',
    summary: 'Known investor — high priority',
    summarySub: 'Time-sensitive: Aileen is asking ahead of round. Reply within 24h. Tone: warm, low-pressure.',
    signals: [
      { kind: 'Sender',    text: 'Partner at Sequoia (verified via LinkedIn) · Tier-1 fund · 12-yr operator history' },
      { kind: 'Reference', text: '"Series B timeline" matches DriveX active fundraise context' },
      { kind: 'Tone',      text: 'Warm, low-pressure, peer-level — no aggressive ask, no deck request yet' },
      { kind: 'History',   text: '2 prior DMs from this sender · both replied within 24h' },
      { kind: 'Urgency',   text: 'High — active fundraise window; reply latency directly affects round dynamics' },
      { kind: 'Action',    text: 'Reply within 24h with calendar link · attach deck on send' },
    ],
    timeline: [
      { label: 'Received',   time: '07:12 AM', state: 'done' },
      { label: 'Classified', time: '07:12:14', state: 'done' },
      { label: 'Drafted',    time: '07:12:21', state: 'done' },
      { label: 'Pending Jamie', time: 'now',   state: 'active' },
      { label: 'Sent',       time: '—',         state: 'pending' },
    ],
  },
  { id: 't2', name: 'Devon Park', role: 'Senior Eng, ex-Stripe',
    cat: 'candidate', time: '07:04',
    preview: 'Saw the DriveX role — interested. Have 8y on payments infra.',
    draft: "Devon — your Stripe background is a strong fit. Sending you the JD and a Calendly. Heads up the team is small and ships fast.",
    confidence: 0.87, reasoning: 'Profile match for Senior Eng role · 8y relevant · Came via referral channel' },
  { id: 't3', name: 'Maya Okafor', role: 'Founder, Linnet Health',
    cat: 'founder-peer', time: '06:48',
    preview: 'Could you intro me to Sarah at Index? Building in similar space.',
    draft: "Maya — happy to. Forwarding to Sarah with a short note. Take ~2 days, she's traveling. Good luck with the round.",
    confidence: 0.82, reasoning: 'Mutual founder · YC W23 batch · Reasonable ask, low cost' },
  { id: 't4', name: 'Tom Beech', role: 'AE, Acmeloop',
    cat: 'vendor', time: '06:32',
    preview: 'Acmeloop can cut your CI bill 40%. 15 min to walk through?',
    draft: "Not the right time — we're locked in with our current setup through Q4. Will reach out if that changes.",
    confidence: 0.76, reasoning: 'Cold vendor pitch · No prior relationship · Polite decline default' },
  { id: 't5', name: 'Priya Rangan', role: 'GP, Lightspeed',
    cat: 'investor', time: '06:18',
    preview: 'Loved the v2 demo. Where are you on the next round?',
    draft: "Priya — appreciate it. Round opens Q3. Want me to add you to the deck list?",
    confidence: 0.88, reasoning: 'Existing investor relationship · Inbound interest · Soft commit territory' },
  { id: 't6', name: 'Ben Sato', role: 'Recruiter, Halyard',
    cat: 'noise', time: '05:54',
    preview: 'Are you open to opportunities? Several CTO roles available…',
    draft: 'Auto-archived.', confidence: 0.94,
    reasoning: 'Generic recruiter outreach · No personalization · Founder, not job-seeking' },
  { id: 't7', name: 'Ravi Mehta', role: 'Founder, Stagehand',
    cat: 'founder-peer', time: '05:41',
    preview: 'Quick q on your hiring funnel — how are you screening eng candidates?',
    draft: "Ravi — we use a 90-min paired build, no take-homes. Happy to walk through it. Easier on a call?",
    confidence: 0.79, reasoning: 'Peer founder · Concrete question · Reciprocity (he answered yours last month)' },
  { id: 't8', name: 'Crypto Daily',
    role: 'Newsletter', cat: 'noise', time: '05:22',
    preview: 'Top 10 AI tokens to watch this week 🚀',
    draft: 'Auto-archived.', confidence: 0.97,
    reasoning: 'Newsletter spam · Off-topic · Auto-archive default' },
];
